version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/fabriciojsil/remote-numbers-fetcher
    steps:
      - checkout
      - run: make test
